# Generated by Django 5.2.8 on 2025-11-15 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('perdido', 'Perdido')], default='novo', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Negócio')),
                ('stage', models.CharField(choices=[('prospeccao', 'Prospecção'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('ganho', 'Fechado (Ganho)'), ('perdido', 'Fechado (Perdido)')], default='prospeccao', max_length=15)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor (R$)')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='accounts.account')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
