# Generated by Django 5.2.8 on 2025-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('perdido', 'Perdido'), ('convertido', 'Convertido')], default='novo', max_length=15),
        ),
    ]
